### ISSUE TITLE
terraform plan always shows conditions/responders change in field teams

### ISSUE THREAD

**Issue by Veres72** [opsgenie/terraform-provider-opsgenie#226]
### Terraform Version
```
Terraform v0.14.7
+ provider registry.terraform.io/opsgenie/opsgenie v0.6.3
```

### Affected Resource(s)
- opsgenie_alert_policy

### Terraform Configuration Files
```hcl
resource "opsgenie_alert_policy" "test" {
  name            = "test"
  team_id         = var.team_id
  message         = "{{message}}"
  continue_policy = true

  filter {
    type = "match-all-conditions"

    conditions {
      field          = "teams"
      expected_value = "my-team"
      not            = false
      operation      = "contains"
      order          = 0
    }
  }
}
```

### Expected Behavior
Terraform apply changes and don't try to change resource in each run 

### Actual Behavior
Terraform apply changes and try to change `conditions ->    field  -> "teams"` in every run 

### Steps to Reproduce
1. Write opsgenie_alert_policy as in example below
2. `terraform plan`
3. `terraform apply`
4. `terraform plan`

```
  ~ resource "opsgenie_alert_policy" "test" {
        id                         = "ID"
        name                       = "test"
        tags                       = []
        # (13 unchanged attributes hidden)
      ~ filter {
            # (1 unchanged attribute hidden)
          ~ conditions {
              ~ field          = "responders" -> "teams"
                # (4 unchanged attributes hidden)
            }
            # (1 unchanged block hidden)
        }
        # (1 unchanged block hidden)
    }
```

**Comment by IskanderNovena** [comment]
This issue still exists.

I'm running into this as well.
**Terraform Version**

```
Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/opsgenie/opsgenie v0.6.10
```

**Terraform Code**

```hcl
resource "opsgenie_integration_action" "azure" {
  integration_id = opsgenie_api_integration.example.id

  create {
    name          = "Create Alert"
    user          = "Azure"
    message       = "[Azure] {{condition_metric_name}} {{condition_operator}} {{condition_threshold}} {{condition_type}} in the last {{condition_window_size}} mins was activated"
    note          = null
    alias         = "{{alias}}"
    source        = "Azure"
    entity        = "{{resource_name}}"
    alert_actions = []
    priority      = P5
    description   = <<DESCRIPTION
Description:
{{description}}
DESCRIPTION

    filter {
      type = "match-any-condition"
      conditions {
        field          = "status"
        operation      = "equals"
        expected_value = "Activated"
      }
      conditions {
        field          = "monitorCondition"
        operation      = "equals"
        expected_value = "Fired"
      }
    }

    responders {
      id   = data.opsgenie_team.responder_team.id
      type = "team"
    }
  }

  close {
    name  = "Close Alert"
    alias = "{{alias}}"
    user  = "Azure"
    note  = null

    filter {
      type = "match-any-condition"
      conditions {
        field          = "status"
        operation      = "matches"
        expected_value = "(Resolved|Deactivated)"
      }
      conditions {
        field          = "monitorCondition"
        operation      = "equals"
        expected_value = "Resolved"
      }
    }
  }
}
```

**Behaviour**

```hcl
# opsgenie_integration_action.azure will be updated in-place
  ~ resource "opsgenie_integration_action" "azure" {
        id             = "<id>"
        # (1 unchanged attribute hidden)

      ~ close {
            name  = "Close Alert"
            # (5 unchanged attributes hidden)

          ~ filter {
                # (1 unchanged attribute hidden)

              ~ conditions {
                  ~ expected_value = "Resolved" -> "(Resolved|Deactivated)"
                  ~ field          = "monitorCondition" -> "status"
                  ~ operation      = "equals" -> "matches"
                    # (2 unchanged attributes hidden)
                }
              ~ conditions {
                  ~ expected_value = "(Resolved|Deactivated)" -> "Resolved"
                  ~ field          = "status" -> "monitorCondition"
                  ~ operation      = "matches" -> "equals"
                    # (2 unchanged attributes hidden)
                }
            }
        }

      ~ create {
            name                                 = "Create Alert"
            tags                                 = []
            # (18 unchanged attributes hidden)

          ~ filter {
                # (1 unchanged attribute hidden)

              ~ conditions {
                  ~ expected_value = "Fired" -> "Activated"
                  ~ field          = "monitorCondition" -> "status"
                    # (3 unchanged attributes hidden)
                }
              ~ conditions {
                  ~ expected_value = "Activated" -> "Fired"
                  ~ field          = "status" -> "monitorCondition"
                    # (3 unchanged attributes hidden)
                }
            }

            # (1 unchanged block hidden)
        }
    }
```

**Comment by IskanderNovena** [comment]
To add, even setting an `order` in the condition doesn't help. The `order` is set to `0` in OpsGenie itself and then triggers another 'change' on a plan and/or apply.

**Comment by PrayagS** [comment]
This issue is faced by us as well.

We have to resort to `ignore_changes` and I don't like that to be honest. Can this be fixed in the provider itself?

**Comment by dil-ddecarvalhogomes** [comment]
+1

**Comment by koushik-swaminathan** [comment]
The field value `teams` under the filters is automatically converted to `responders` in the public API. I tried calling the public API directly to create an alert policy and looks like `teams` has been deprecated. I request you to use `responders` field to add teams instead. We will be updating the documentation as well as the code to make sure `teams` cannot be used as a valid value anymore. 
If you check the UI for adding an alert policy, you can notice that `teams` does not show up anymore. 
<img width="984" alt="Screenshot 2023-07-25 at 4 00 16 PM" src="https://github.com/opsgenie/terraform-provider-opsgenie/assets/82563281/974c2979-9d62-46df-81a2-286aa21ead8e">

**Comment by koushik-swaminathan** [comment]
Closing the issue since there has not been any replies.

**Comment by guidojw** [comment]
> This issue still exists.
> 
> 
> 
> I'm running into this as well.
> 
> **Terraform Version**
> 
> 
> 
> ```
> 
> Terraform v1.1.6
> 
> on linux_amd64
> 
> + provider registry.terraform.io/opsgenie/opsgenie v0.6.10
> 
> ```
> 
> 
> 
> **Terraform Code**
> 
> 
> 
> ```hcl
> 
> resource "opsgenie_integration_action" "azure" {
> 
>   integration_id = opsgenie_api_integration.example.id
> 
> 
> 
>   create {
> 
>     name          = "Create Alert"
> 
>     user          = "Azure"
> 
>     message       = "[Azure] {{condition_metric_name}} {{condition_operator}} {{condition_threshold}} {{condition_type}} in the last {{condition_window_size}} mins was activated"
> 
>     note          = null
> 
>     alias         = "{{alias}}"
> 
>     source        = "Azure"
> 
>     entity        = "{{resource_name}}"
> 
>     alert_actions = []
> 
>     priority      = P5
> 
>     description   = <<DESCRIPTION
> 
> Description:
> 
> {{description}}
> 
> DESCRIPTION
> 
> 
> 
>     filter {
> 
>       type = "match-any-condition"
> 
>       conditions {
> 
>         field          = "status"
> 
>         operation      = "equals"
> 
>         expected_value = "Activated"
> 
>       }
> 
>       conditions {
> 
>         field          = "monitorCondition"
> 
>         operation      = "equals"
> 
>         expected_value = "Fired"
> 
>       }
> 
>     }
> 
> 
> 
>     responders {
> 
>       id   = data.opsgenie_team.responder_team.id
> 
>       type = "team"
> 
>     }
> 
>   }
> 
> 
> 
>   close {
> 
>     name  = "Close Alert"
> 
>     alias = "{{alias}}"
> 
>     user  = "Azure"
> 
>     note  = null
> 
> 
> 
>     filter {
> 
>       type = "match-any-condition"
> 
>       conditions {
> 
>         field          = "status"
> 
>         operation      = "matches"
> 
>         expected_value = "(Resolved|Deactivated)"
> 
>       }
> 
>       conditions {
> 
>         field          = "monitorCondition"
> 
>         operation      = "equals"
> 
>         expected_value = "Resolved"
> 
>       }
> 
>     }
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> **Behaviour**
> 
> 
> 
> ```hcl
> 
> # opsgenie_integration_action.azure will be updated in-place
> 
>   ~ resource "opsgenie_integration_action" "azure" {
> 
>         id             = "<id>"
> 
>         # (1 unchanged attribute hidden)
> 
> 
> 
>       ~ close {
> 
>             name  = "Close Alert"
> 
>             # (5 unchanged attributes hidden)
> 
> 
> 
>           ~ filter {
> 
>                 # (1 unchanged attribute hidden)
> 
> 
> 
>               ~ conditions {
> 
>                   ~ expected_value = "Resolved" -> "(Resolved|Deactivated)"
> 
>                   ~ field          = "monitorCondition" -> "status"
> 
>                   ~ operation      = "equals" -> "matches"
> 
>                     # (2 unchanged attributes hidden)
> 
>                 }
> 
>               ~ conditions {
> 
>                   ~ expected_value = "(Resolved|Deactivated)" -> "Resolved"
> 
>                   ~ field          = "status" -> "monitorCondition"
> 
>                   ~ operation      = "matches" -> "equals"
> 
>                     # (2 unchanged attributes hidden)
> 
>                 }
> 
>             }
> 
>         }
> 
> 
> 
>       ~ create {
> 
>             name                                 = "Create Alert"
> 
>             tags                                 = []
> 
>             # (18 unchanged attributes hidden)
> 
> 
> 
>           ~ filter {
> 
>                 # (1 unchanged attribute hidden)
> 
> 
> 
>               ~ conditions {
> 
>                   ~ expected_value = "Fired" -> "Activated"
> 
>                   ~ field          = "monitorCondition" -> "status"
> 
>                     # (3 unchanged attributes hidden)
> 
>                 }
> 
>               ~ conditions {
> 
>                   ~ expected_value = "Activated" -> "Fired"
> 
>                   ~ field          = "status" -> "monitorCondition"
> 
>                     # (3 unchanged attributes hidden)
> 
>                 }
> 
>             }
> 
> 
> 
>             # (1 unchanged block hidden)
> 
>         }
> 
>     }
> 
> ```
> 
> 
> 
> 

@IskanderNovena I am very late to the issue, but saw you're setting `note` to null:

What is the result of this? I am trying to unset some fields like `note`, tried using empty string or `null` but in both cases on Opsgenie `{{note}}` still shows up while I expect it to be empty

**Comment by IskanderNovena** [comment]
@guidojw I can't answer your question. I've left the company where I worked on this 2 years ago, and am not using OpsGenie anymore.
